### ISSUE TITLE
further actions on the deleted and downvoted posts

### ISSUE THREAD

**Issue by AliCihan** [julianlam/nodebb-plugin-dwnvtr#2]
when 3 points on the corner is clicked to purge the post... if the post is downvoted and transparent the options are not clickable... 

To click the purge option, I have to shrink the window size of the browser so that the options will appear from the bottom of the page...

Nodebb 1.13.2 with Firefox, the post had two downvotes 

(Additionally, it would be great if options are not transparent, because it makes it harder to see if there are more than 5 negative votes)

**Comment by julianlam** [comment]
v0.1.2
