### ISSUE TITLE
deletion of a post doesn't cause further fading

### ISSUE THREAD

**Issue by AliCihan** [julianlam/nodebb-plugin-dwnvtr#3]
If a post is downvoted, deletion of the post doesn't cause fading as normal posts... 

If several subsequent posts are downvoted as -1, -2, -3... deletion is not obvious with changing fade... 

I think downvoting fading overrides the deletion fading... it would be better if deletion causes the same pattern for all posts independent of the number of votes it got.

**Comment by julianlam** [comment]
:smirk:
